filter:
  excluded_paths:
    - 'tests/'
    - 'tools/'

build:
  image: default-bionic
  dependencies: { override: true }
  nodes:
    analysis: # see https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/
      environment:
          php: 8.4 # Use a standard version already in the image
      project_setup: { override: true }
      tests: { override: true }

tools:
  external_code_coverage: true
